
<table class="table table-bordered table-striped table-hover table-condensed">
  <tbody>
    <tr>
      <th><label>@lang('validation.attributes.organization')</label></th>
      <td><label>{{$obj->user->place->organization}}</label></td>
    </tr>
    <tr>
      <th><label>@lang('validation.attributes.user_id')</label></th>
      <td><label>{{$obj->user->name}}</label></td>
    </tr>
    <tr>
      <th><label>@lang('validation.attributes.place_id')</label></th>
      <td><label>{{$obj->user->place->getCompleteLabelAttribute()}}</label></td>
    </tr>
    <tr>
      <th><label>@lang('validation.attributes.gender')</label></th>
      <td><label>@lang('application-constant.GENDER.'.$obj->user->gender)</label></td>
    </tr>
    <tr>
      <th><label>@lang('validation.attributes.dob')</label></th>
      <td><label>{{$obj->user->dob}}</label></td>
    </tr>
    <tr>
      <th><label>@lang('validation.attributes.marriage_status')</label></th>
      <td><label>@lang('application-constant.MARRIAGE_STATUS.'.$obj->user->marriage_status)</label></td>
    </tr>
    <tr>
      <th><label>@lang('validation.attributes.address')</label></th>
      <td><label>{{$obj->user->address}}</label></td>
    </tr>
    <tr>
      <th><label>@lang('validation.attributes.phone')</label></th>
      <td><label>{{$obj->user->phone}}</label></td>
    </tr>
    <tr>
      <th><label>@lang('validation.attributes.occupation')</label></th>
      <td><label>{{$obj->user->occupation}}</label></td>
    </tr>
    <tr>
      <th><label>@lang('validation.attributes.latest_degree')</label></th>
      <td><label>{{$obj->user->latest_degree}}</label></td>
    </tr>
    <tr>
      <th><label>@lang('validation.attributes.shinjin_from')</label></th>
      <td><label>{{$obj->user->shinjin_from}}</label></td>
    </tr>
  </tbody>
</table>